main: art.dankpiss.CaveGenerator.Main
name: ${project.artifactId}
version: ${project.version}
api-version: 1.19
website: ${plugin.website}
author: ${plugin.author}
description: ${project.description}
commands:
  erode:
    description: "Erode caves with acid"
    usage: /erode help